### ISSUE TITLE
Supporting the Ecosystem

### ISSUE THREAD

**Issue by LucioFranco** [rustasync/team#102]
Hi everyone!

I think one of the main goals that the rust net web wg should focus on is not just exploring futures 0.3 but also supporting the community of users and maintainers. I think there are two sides to this, one is creating a really good consumer-facing book on how to work with futures and a place that really primes and sets people up for success with futures. The second is to create guides for library maintainers that use futures 0.1 on how to migrate to 0.3 easily. These two goals to me should enable the ecosystem and its users to reap the benefits of futures 0.3 quicker.

For the book, we already have a pretty good book [here](https://github.com/rust-lang/async-book) but it is still very light on its material. I would like to see kind of what the tokio.rs site was going after for its docs but more general and applied to futures 0.3. I think this is something that should be a large effort by the net web wg. I think it should include chapters on how to use tide, write a proxy, write clients and work with databases. Any more use cases are welcome, I'm sure I did not cover all of them. But to me, the goal of this is to help people get started as the biggest area of weakness right now for futures is documentation.

Not only do we need to write a book but doing weekly blog posts and/or making tutorial videos is another thing that could greatly decrease the barrier of entry for using futures.

For the guides, I'm not 100% sure how we should go about this but I would like to see a guide on how to use the compat layers and what options library maintainers have to move to the new futures 0.3. This may also mean that as a team we spend some time exploring on how to migrate certain libraries to 0.3 and use that experience as a stepping stone for writing the guides.

I think one of the biggest goals that this wg should have is to enable the producers and consumers of the ecosystem. Enabling them to build the best software they can build with such a great language like rust.

I probably missed some stuff but I think this properly summarizes what I was thinking. Feel free to comment on any ideas, I mostly just wanted to start a conversation around this.

cc @yoshuawuyts @bIgBV

**Comment by yoshuawuyts** [comment]
@LucioFranco thanks so much for starting the discussion! I quite like everything you've raised so far. I've tried summarizing the points you've made into a brief overview:

- async-book
  - Look to tokio's docs for inspiration, but generalize it further, and apply to std futures
  - Chapter on Tide
  - Write a client
  - Work with databases
- futures migration guide
  - cover the compat layer
  - cover migration from futures 0.1 to 0.3/std
    - consider using (recurring) examples
- weekly blog posts / videos

---

A challenge the WG currently has is that we have a presence on 4 websites currently, and if we add a book that'd make 5. I'm thinking perhaps for a first bit it might perhaps be good to perhaps start with just one book for the general futures documentation + migration guides.

It might perhaps also be good to not to include Tide in this while the API is still actively developed. That would prevent us from possibly being blocked at times, and having to go back and rewrite things. I def like the idea of looking at other docs (in particular Tokio), and see what we can learn from them.

Also worth noting is that there's a new database WG forming, and they might be able to assist with covering everything about database bindings. Perhaps talking to them about writing docs would be good.

@LucioFranco More blog posts & videos would be very cool! We have a blog on [rustasync/team#gh-pages](https://github.com/rustasync/team/tree/gh-pages), and adding to that would be awesome. Do you have any ideas for posts or videos in particular?

I'm very excited for all this!

**Comment by yoshuawuyts** [comment]
Also in chat @LucioFranco linked the outline of the Tokio doc effort was linked which might be great to take inspiration from: https://github.com/tokio-rs/doc-push/tree/master/outline.

**Comment by LucioFranco** [comment]
@yoshuawuyts I think that summary is pretty good, though I would probably add a proxy or another example that heavily uses channels to show how they can be used.

I think it may also be interesting to take patterns used from production systems that use futures I'm thinking linkerd as a good candidate on how to build high throughput systems.

As for videos, Im not totally sure but I do really like the 5min videos on rust that ryan has started and doing something similar for futures would be good.
