### ISSUE TITLE
Async Ecosystem Working Group Meeting #14

### ISSUE THREAD

**Issue by xenith** [rustasync/team#113]
Our next meeting is **Thursday 09-05-2019 at 16:00 UTC**. **(Please note the rescheduled date)**

Add agenda items here: [Dropbox Paper: Rust Async Ecosystem Meetings](https://paper.dropbox.com/doc/Rust-Async-Ecosystem-Meetings--AY0P2mS~oTtWMNAMOtQFs~eBAg-lsZeIpXH6yHQ93zlf4vrM).

We'll be holding open office hours, so if you have any questions about Rust and Web, feel free to add a bullet point to the agenda!

We meet over text on Discord, so make sure to sign up and join the Rust channel before the meeting. Here is our meeting room: [Rust Discord #wg-async-ecosystem](https://discordapp.com/channels/442252698964721669/474974025454452766).

**Anyone interested in async Rust is invited to join!** Yes, that includes _you_!

**Comment by fairingrey** [comment]
Looks like we'll have to reschedule this meeting or meet next week -- the leads weren't here today :(

**Comment by xenith** [comment]
Updated with the new date of May 9th.
