### ISSUE TITLE
Async ecosystems newsletter/blog post #1

### ISSUE THREAD

**Issue by LucioFranco** [rustasync/team#142]
As part of our new effort to reach out more into the ecosystem and communicate with users of async runtimes, we will be publishing monthly (hopefully) blog posts around info related to the ecosystem.

Contents (most of these are just ideas we are all open to more so please leave a comment with more ideas):

- Discuss what runtimes are available (async-std and tokio) and their paths for future releases.
- Discuss the schedule for async/await and the futures crate.
- Discuss resources available, async book, async-std book and tokio.rs.
- Discuss channels for getting help aka a channel on rust community discord that we can link too. cc @tinaun 
- Discuss how you can get involved with rustasync and other communities!

Any other ideas are very much appreciated!

**Comment by AZanellato** [comment]
Would be nice to have something talking about the value in async and why it is worth doing it 😁

**Comment by LucioFranco** [comment]
@AZanellato This chapter should answer that https://rust-lang.github.io/async-book/01_getting_started/02_why_async.html but we can link to it for sure!
