### ISSUE TITLE
Domain web page to "stage 1"

### ISSUE THREAD

**Issue by aturon** [rustasync/team#21]
Get initial draft of the content for the networking landing page to @ashleygwilliams.

**Comment by bIgBV** [comment]
I think https://www.arewewebyet.org/ has curated an amazing amount of content regarding the current state of the networking ecosystem. Is there any way we can leverage that?

**Comment by yoshuawuyts** [comment]
@bIgBV ohh, that's a really good suggestion! I'm not sure if [their curators page](https://www.arewewebyet.org/curators/) is still up to date, but I reckon it'd be great if we could get them involved!
