### ISSUE TITLE
Review web frameworks

### ISSUE THREAD

**Issue by aturon** [rustasync/team#27]
Conduct a comprehensive survey of the existing Rust web frameworks, their status and attributes, and compare against what's readily available in other major languages.

**Comment by tinaun** [comment]
this is from last october but i still find it interesting to read, and could be used as a baseline for further work (cc @icefoxen)

https://wiki.alopex.li/AnOpinionatedGuideToRustWebServers

**Comment by icefoxen** [comment]
I do intend to update that sometime in late 2018.  If you want I could do it sooner, I guess.

**Comment by alinex** [comment]
Did you also had a look on actix-web? Looks also very good.
