### ISSUE TITLE
Review general protocol implementations

### ISSUE THREAD

**Issue by aturon** [rustasync/team#28]
Collect info on Rust implementations of protocols like http, http/2, grpc, thrift, and so on. What is the status of each?

**Comment by aajtodd** [comment]
I know of at least 3 gRPC implementations:

1. https://github.com/stepancheg/grpc-rust
    * Pure rust
    * Built on [protobuf](https://crates.io/crates/protobuf) and [httpbis](https://crates.io/crates/httpbis)
    * Futures based
1. https://github.com/pingcap/grpc-rs
    * Rust wrapper around gRPC C core
    * Futures based
1. https://github.com/tower-rs/tower-grpc/
    * Pure Rust
    * Built on [prost](https://crates.io/crates/prost) and [h2](https://crates.io/crates/h2)
    * Futures based

I know some people are fairly involved already in tower-grpc.

On the one hand the work pingcap did wrapping the official gRPC C core makes a lot of sense and provides a decent way to stay up to date with gRPC. On the other it is not a showcase for Rust really (not sure if that is a goal or not). 

There are many challenges to gRPC outside of the networking part including protubuf support for Rust, code generation for service stubs, etc. 

In my opinion the goal for a gRPC library in Rust should be to gain official support by the gRPC project and be incorporated into that ecosystem. Most languages are wrappers around the C core but there are exceptions (grpc-java and grpc-go are completely written in their respective languages). Being officially recognized as part of the gRPC project would go a long way to breaking down barriers to adopting Rust by companies looking to use Rust for network services/gRPC. I know at one time the gRPC maintainers indicated they would be willing to pull a high enough quality implementation into the main repo, not sure if their stance is the same or not.

**Comment by polachok** [comment]
Kafka
====
I know of 3 implementations:
 * [kafka](https://github.com/spicavigo/kafka-rust)
   - pure rust
   - synchronous
   - only older protocol supported (0.8.2)
   - doesn't fully support consumer groups & rebalancing
* [rdkafka](https://github.com/fede1024/rust-rdkafka)
   - bindings to rdkafka C/C++ library
   - sync and async (with futures)
   - all features supported
* [tokio-kafka](https://github.com/flier/tokio-kafka)
  - not ready, not published, unstable
  - async, uses tokio
  - older protocols supported

Personal (production) experience
---------------------------------
kafka-rs is ok, but doesn't support newer protocol versions which are much more efficient (better compression, etc).
tokio-kafka is promising, but not very usable at the moment. I think with community support it could be made into a production class library.
rdkafka is what we use in production, it's ok, but api looks a bit weird to me (subjective).
