### ISSUE TITLE
stdnet Crate

### ISSUE THREAD

**Issue by stephanbuys** [rustasync/team#34]
Hi all, last year I submitted a RFC to get mac addresses added to the std lib, it wasn't a good fit, but after seeing the `stdweb` crate's trajectory and becoming a part of this effort I suggest we create a `stdnet` crate.

This crate will attempt to be the natural home for Structs, Parsers and sundry for re-usable datatypes in the networking area.

There is no reason why everyone should re-implement something like a TCP or IP header, for example.

There is a lot of prior art out there, if you have crates, parsers, etc that already cover this please indicate if you would be interested in a re-usable crate, what criteria it would have to meet and if you would be interested in contributing? 

Also interested in what should be in such a crate, I would start with all the OSI layer 2 and 3 protocols.

**Comment by stephanbuys** [comment]
@dlrobertson would something like this "`stdnet`" idea be appealing in the embedded space?

**Comment by mrmonday** [comment]
> There is no reason why everyone should re-implement something like a TCP or IP header, for example.

My experience has shown that everyone who goes near this level will just implement it themselves. @dlrobertson mentions several implementations. Yes, it's always the same, but you want full control over it. And the difficult part is the protocols build on top, not the packets themselves (save the bit-shifting, but that's easy to write once then forget about).

Perhaps a more interesting thing to think about would be a way to have these different implementations interoperate. It would be amazing to have a way to compose packets from different libraries, whether they're high level abstractions over the packets, or zero-overhead views.

I think there's definitely room for a stdnet, but I also think it's very difficult to figure out what to put in one.

**Comment by stephanbuys** [comment]
@mrmonday and @dlrobertson thanks for the excellent feedback - I agree with the challenges this could face, I would also suggest to keep it really simple. I would even go as far as just starting with the Types themselves, I noticed `mio` supports extensions, that could be a way to implement serialization and serialization. Having a standard set of Types will enable some code interop, then one can dive into specialisation (how to parse, and use).

Some base that can be shared around between crates, as well as a set of Enums, etc for the meanings of the bit flags - etc. Simple stuff. A little bit like the role the `http` fulfills could be a starting point?

**Comment by Nemo157** [comment]
I like this idea. Two comments:

1. Is it a good idea to have this in a single crate, covering all protocols at different levels of the stack is a very disparate set of data types that only some crates will need. Instead should it be an organization defining API standards and sets of tools to easily create different crates for different protocols. Alternative structure could be to have a single crate with different feature flags for different protocols.

2. I started [a crate for CoRE parameters](https://github.com/nemo157/core-parameters-rs) a while back. I think this seems like exactly the sort of thing that this crate could be covering (although it's application layer/application layer+ not the 2/3 mentioned above). The next step I haven't gotten around to yet is to add scripts to pull down the data from the registry and actually generate associated constants for the different parameters. Building a generic framework for these sorts of scripts is one piece that could definitely be useful.

**Comment by polachok** [comment]
I agree with @Nemo157 that this should be an organization (`rust-networking`?), not a crate. Different protocols don't really share much datatypes in my experience. And it seems against rust philosophy (many small crates) to put a lot of unrelated stuff in one crate.

**Comment by stephanbuys** [comment]
Does anyone know what the implications are on resulting binaries on a split-crate with good module use (like `std`) strategy? It there is no real cost to having a central place for the re-usable parts it would be an argument for crate features? The embedded folks might be affected, but I'm not sure how smart the compiler is.
