### ISSUE TITLE
End-to-end user story: Tractor Control Channel

### ISSUE THREAD

**Issue by bryanburgers** [rustasync/team#36]
There was recently talk on Discord #wg-net about gathering end-to-end user stories that aren’t REST or HTTP servers.

Here is a real world example of an application that exists that I would like to write in Rust. It is currently written in Node.js (server) and C++ (client).

I’m not sure how representative it is.

## Tractor Control Channel

The company I work for builds displays and cellular modems to put in agricultural tractors. When possible, we maintain a Control Channel between the display, over the cellular modem, back to our servers.

This Control Channel has the following requirements.

* Low-ish bandwidth – our customers pay for the data plan; we don’t want to use all of their data; currently about 22MB/month. To achieve this, we typically compress the data stream.
* Fast communication – when a message is generated from either side, it should be received by the other side on the order of seconds, not minutes. To achieve this we use a constant TCP connection.
* Secure – the channel must be encrypted.

To accomplish this, the client opens a TCP connection to one of our servers and maintains it for as long as it is open. The data sent over the TCP connection is a stream of length-prefixed protocol buffer messages, compressed with standard Gzip, encrypted with standard TLS, and sent over the TCP connection.

The communication is two-way (i.e. we can’t replicate it using a request/response pattern). Some examples of this:

* When the client has telemetry data, to send, it sends it. The service does not respond to every telemetry message, but occasionally responds in aggregate.
* When the client wants to upload a file, it notifies the service, which responds with how to upload the file (like the hostname, username, password of an out of band FTP upload)
* When the service wants the client to download a file, it notifies the client with out of band information, and the client downloads the file, providing periodic progress updates (e.g. “17% done”)
* There are more examples of both sides sending control messages to the other, but it’s probably belaboring the point.

Both sides take the Control Channel messages and store them in databases. On the client side, this is typically SQLite. On the server side, this is MySQL, Kinesis (AWS-hosted event stream), etc.

Roadblocks when moving from a Tokio example to a full application:

* It’s not just a request/process/response pattern. We need to write to streams based on requests, based on external events, based on timers. How to do that was unclear (clone the TCP writer? Pipe an MPSC into the writer, and clone the sender side? Other?)
* How to layer Gzip and TLS into the stream?
* How to separate business logic from network-level code?
* What to do when business logic needs to use a sync crate?

**Comment by bryanburgers** [comment]
To be clear: I’m not looking for help writing this application. I’m fairly certain this Control Channel will not get a major rewrite.

It’s just an example of the sorts of things I would like to use Rust for in the future.

**Comment by aajtodd** [comment]
@bryanburgers I have a similar user story/experience. The use case I was investigating a while back was layering gRPC on top of a proprietary protocol that is inherently not request/response. The state machine is very custom and includes a hodge podge of concepts including streaming, fire and forget, key exchange, etc. The simple examples were a far cry from being able to extrapolate to how to actually use things like tokio and futures. I would like to help remedy that situation.

**Comment by djc** [comment]
In the mid- to long-term, I think the QUIC protocol will be able to help with these sorts of use cases. Have a look at [quinn](https://github.com/djc/quinn) or [quicr](https://github.com/Ralith/quicr) if you're interested.
