### ISSUE TITLE
Relationship between wg-net and async disk I/O?

### ISSUE THREAD

**Issue by code-ape** [rustasync/team#41]
This WG is an important effort in the Rust community related to the development of networking libraries and applications. However, by the nature of high speed networking, this is has resulted in a lot of discussion and work related to futures, async / await, and executors for them such as Tokio. I wanted to pose the question of whether it makes sense for this group to also include disk I/O as well?

I know that, obviously by the groups current name, the answer is no. However, with so much interest in high performance async code, it seems like a logical fit. As someone who has worked on high performance I/O systems, async disk I/O has not received nearly as much attention as async network I/O. While there are reasons for this phenomenon (file system support, OS support of file system features, creating a scheduler, etc) the fact remains that applications which are engineered for high speed, async network I/O can benefit from having a shared abstraction model which also encompasses disk I/O. The SeaStar framework, used by ScyllaDB and referenced in some other issues of this group, is one such example of this.

**Comment by jsgf** [comment]
I think that async filesystem IO is pretty niche and limited in domain to things like databases compared to async networking. Aside from async file IO with aio, Tokio's `blocking` call to make sync filesystem operations in worker threads is close to state of the art (which is pretty sad). Without a lot more effort on the kernel side, I don't see this improving.
I gather the story on the Windows side is a lot better, but I don't have any direct knowledge/experience. Maybe there's more of a conversation to be had there.

**Comment by jkozlowski** [comment]
I am working on an issue for this that summarises my thinking, but it's not finished yet (hard to find time with a newborn :))

Here it is @code-ape if you're interested: https://www.evernote.com/shard/s142/sh/f9457cfa-b52a-4f77-a01c-09a84bbb2244/0623cf4432cea382819ef049eee39b9a

**Comment by tynril** [comment]
I don't think the WG name should limit doing work on this, if you're interested. There's also value in sharing traits between network-based async operations and file-based, in my opinion.

**Comment by yoshuawuyts** [comment]
>  it would be helpful to have some practical uses of futures+ to make sure tokio-specific assumptions don't get baked in (...)

I believe the fine folks working on Fuschia OS are doing a great job at this! From what I've seen they make heavy use of Futures + async/await throughout their kernel, and have been one of the driving forces for dropping `Error` from the `Task` trait in `futures@0.3.0` because it didn't make sense for every part of the kernel (if I got that right).

More non-Tokio stakeholders would ofcourse be great, but I think we're probably in a reasonable spot already!

**Comment by jsgf** [comment]
Yeah, they're doing some cool stuff and after talking to them I'm convinced the non-Tokio use-cases are well represented.

**Comment by carllerche** [comment]
@yoshuawuyts there are currently 0 Tokio stakeholders on the futures team, fwiw.

**Comment by Ralith** [comment]
I strongly disagree that async filesystem I/O is niche; blocking on disk is not a good use of CPU time for any application, and can severely impair responsiveness. The unfortunate reality is that OS support is poor and tends to silently and unpredictably degrade to blocking, but even hacky solutions like tokio-fs are useful.

**Comment by KizzyCode** [comment]
You don't always have a responsive IO – a slow thumb drive that is overloaded, an external HDD that needs to spin up, a (FUSE) network filesystem like SSHFS... and each program that uses blocking-IO blocks until the call is completed.
For some applications it might be acceptable to block until the call is completed, but for most applications it's quite annoying – IMHO non-blocking IO should be default and if there's a way to use this easily... ❤️
