### ISSUE TITLE
IO traits for datagram based protocols

### ISSUE THREAD

**Issue by Nemo157** [rustasync/team#43]
[`futures-io`](https://rust-lang-nursery.github.io/futures-doc/0.3.0-alpha.2/futures_io/index.html) currently includes two traits for streaming IO, these are very similar to the traits of the same name that [`tokio::net::TcpStream`](https://docs.rs/tokio/0.1.7/tokio/net/struct.TcpStream.html) implements and will hopefully be very useful for developing transport agnostic higher-level protocols (e.g. for transparently inserting TLS). On the other hand [`tokio::net::UdpSocket`](https://docs.rs/tokio/0.1.7/tokio/net/struct.UdpSocket.html) currently implements no useful traits, so it would be more effort to have a protocol that is agnostic over an insecure UDP connection or a secured DTLS connection.

This abstraction may also be useful in lower layers of a networking stack, e.g. while TCP presents a streaming interface to higher layers it is built on top of the datagram based IP layer, so a usermode TCP/IP stack could use such an abstraction.

One alternative would be to avoid defining new traits and instead standardise the ecosystem around something like `Stream<Item = Bytes> + Sink<Item = Bytes>`. At first glance this seems like it would have issues in supporting allocation/copy-less usecases, but I think it's definitely worth looking into.

(CC @levex, @ralith from our discord discussion)

**Comment by Ralith** [comment]
This seems useful, albeit a bit esoterically. I'd like to add that hardwiring in `io::Error` should be avoided this time around, as it's often inappropriate.

**Comment by tynril** [comment]
This could also be great for testing, by allowing the implementation of mock transports.

Is this one of the trait we should put in `stdnet`?

**Comment by Nemo157** [comment]
> I'd like to add that hardwiring in io::Error should be avoided this time around, as it's often inappropriate.

Definitely, I’ve been meaning to open an issue to discuss changing that for the read/write traits as well.
