### ISSUE TITLE
wg-net newsletter #2

### ISSUE THREAD

**Issue by yoshuawuyts** [rustasync/team#60]
Let's collect content for the next issue of the Net Web WG newsletter here! :sparkles:

**Comment by djc** [comment]
Ping? I'd be interested in what's been going on, at least.

**Comment by yoshuawuyts** [comment]
I think at the moment the [Rust Networking WG Twitter account](https://twitter.com/RustNetWG) has the largest aggregation of news. We haven't had a meeting with all net WGs since September, which explains part of the hiccup here.

**Comment by aturon** [comment]
Let's close this out, since we've moved to instead hosting meeting minutes.

(That said, @yoshuawuyts have we been posting those to internals and twitter when they happen?)

**Comment by yoshuawuyts** [comment]
@aturon no we haven't. Perhaps we should start PRing them to the repo after we're done with the meeting.

@gruberb would you be up for doing this?

**Comment by gruberb** [comment]
@yoshuawuyts Yes, definitely! Should we have one document per meeting or an ongoing one?

If we split, I can create a PR for every meeting so far and create separate markdown files for each meeting!

**Comment by yoshuawuyts** [comment]
@gruberb I think a doc per meeting would be ideal; allows us to easily refer back just by looking at the file name ^__^
